server:
  port: 4444

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pvalderas/es.books.microservices.serverconfig

security:
  basic:
    enabled: true
  user:
    name: admin
    password: '{cipher}baa9a591edb3925706ccc5b2144758cc8ed7e7bc05bfc2fa6fa57210f9688c44'
